# Site settings
# in the templates available like {{ site.myvariable }}.
title: 个人网站.
email: 806197998@qq.com
brand: 天际小行星
headline: 中大南方16级网络与新媒体学生
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "个人作品展示网站" # the subpath of your site, e.g. /blog
url: "https://sssakuraiii.github.io/Liushiying.github.io/" # the base hostname & protocol for your site
copyright: 2019 网络与新媒体, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: 806197998@qq.com
phone: 不会轻易告诉你哦
